# Generated by Django 3.2 on 2021-06-17 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter original language of the book (e.g. English)', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.OneToOneField(help_text='Select a language for this book', null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.language'),
        ),
    ]
