# Generated by Django 3.2 on 2021-07-01 07:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_usertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='user_token',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique token for this user', unique=True, verbose_name='Token'),
        ),
    ]
